// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';

export function GenerateQR(arg1:string):Promise<string>;

export function GetAppInfo():Promise<app.AppInfo>;

export function GetEngineStatus():Promise<app.EngineStatus>;

export function GetUserPosition():Promise<app.UserPosition>;

export function GetWebServerURL():Promise<string>;

export function IsWebServerRunning():Promise<boolean>;

export function ToggleWebServer():Promise<string>;
