// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenerateQR(arg1) {
  return window['go']['app']['App']['GenerateQR'](arg1);
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetEngineStatus() {
  return window['go']['app']['App']['GetEngineStatus']();
}

export function GetUserPosition() {
  return window['go']['app']['App']['GetUserPosition']();
}

export function GetWebServerURL() {
  return window['go']['app']['App']['GetWebServerURL']();
}

export function IsWebServerRunning() {
  return window['go']['app']['App']['IsWebServerRunning']();
}

export function StartMobileServer() {
  return window['go']['app']['App']['StartMobileServer']();
}

export function ToggleWebServer() {
  return window['go']['app']['App']['ToggleWebServer']();
}
